### ISSUE TITLE
Иконка в трее не меняется при смене раскладке.

### ISSUE THREAD

**Issue by Aleksandern** [grompe/kbdasm#5]
Здравствуйте.
Спасибо за решение. Есть такая проблема.
Раскладка переключается но иконка в трее не меняется.
Windows 10 (64)
![kbdasm](https://cloud.githubusercontent.com/assets/5274465/24999380/7e60e8ae-2067-11e7-979b-b61f22437cfe.gif)

**Comment by grompe** [comment]
Она и не должна меняться, технически это одна раскладка с двумя наборами символов.
Если угодно, можно поставить какую-нибудь программу, показывающую состояние Caps Lock иконкой.

**Comment by Aleksandern** [comment]
Оставлю тогда ссылку на такую программу если вы не против (open source)
https://github.com/roidayan/KeyboardIndicator
http://roidayan.com/keyboard-indicator/
