### ISSUE TITLE
Не везде переключается раскладка

### ISSUE THREAD

**Issue by Aleksandern** [grompe/kbdasm#6]
Раскладка не везде переключается на русский (см. скриншоты)
Windows 10 (64)
![1111](https://cloud.githubusercontent.com/assets/5274465/25048126/df4ed290-2164-11e7-93e7-e34837986efa.PNG)
![2222](https://cloud.githubusercontent.com/assets/5274465/25048130/e131d184-2164-11e7-8a9e-bf50ce854691.png)

**Comment by grompe** [comment]
Похоже, разработчики этих текстовых полей в Windows 10 забыли о существовании SGCAPS в раскладке или бездумно решили обрабатывать ввод самостоятельно.

**Comment by Aleksandern** [comment]
Не знаю почему, может обновления недавние помогли, но переключение языков в этих окнах работает нормально теперь.

**Comment by grompe** [comment]
Доделывают свой beta-quality product. Рад, что всё разрешилось.
