### ISSUE TITLE
kbdusru_undead перемещение курсорных клавиш

### ISSUE THREAD

**Issue by zapominai** [grompe/kbdasm#7]
Возможно ли в kbdusru_undead.asm эмулировать нажатие курсорных клавиш?

Например, я хочу по нажатию RAlt+j опускать курсор вниз, как ни пробовал прописать это в секции:

vkrow4 "J",           SGCAPS, "j",      "J",      WCH_DEAD, WCH_DEAD
vkrow4 "J",           0,      "о",      "О",      "j",      "J"

Нужного эффекта не добился. Пробовал разные коды клавиш.

**Comment by grompe** [comment]
Назначение клавиш происходит в два этапа: сканкод в vkey, и vkey в wchar.
В первом можно поменять нажатую кнопку, во втором (в комбинации с Shift, Ctrl, Alt, etc. — набираемый символ).
Нельзя модификатор+vkey превратить в другой vkey средствами раскладки.
Тут требуется внешняя программа.

**Comment by zapominai** [comment]
Понял, спасибо за объяснения, буду искать такой софт. Попробовал 3-4 ремапера, всё не то.
Либо не позволяет назначит такую замену, либо работает не везде.
