### ISSUE TITLE
Возможность включения и одновременной работы стандартных сочететаний клавиш

### ISSUE THREAD

**Issue by deprino** [grompe/kbdasm#8]
Подскажите пожалуйста, можно ли помимо CAPSLOCK оставить задействованным текущее переключение (CTRL+SHIFT) и добавить ещё одно (ALT+SHIFT) дабы на компьютере работали все популярные сочетания клавиш для переключения, и если да, то как это сделать?

**Comment by grompe** [comment]
Переключение раскладок — это в общем-то не функция раскладки. Так что нет.
Переключение с помощью Caps Lock тут является хаком, основанным на том, что в режиме SGCAPS можно вводить другие символы. Система же видит единственную раскладку.

Для добавления клавиатурных сочетаний нужно смотреть в сторону хука WH_KEYBOARD_LL.

**Comment by grompe** [comment]
Собственно, [lswitch](https://github.com/valodzka/lswitch/blob/master/lswitch/lswitch.c) — программа для (честного) переключения раскладок по Caps Lock'у. Можно подредактировать, добавив туда нужные сочетания.
